---
abstract: 'Catalyst based application'
author:
  - 'Catalyst developer'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Avarpics
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Model::Adaptor: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Plugin::Unicode: 0
  Catalyst::Runtime: 5.80016
  Catalyst::View::TT: 0
  Config::General: 0
  Date::Calc: 0
  File::Slurp: 0
  Modern::Perl: 0
  Moose: 0
  POSIX: 0
  WWW::Mechanize: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
